name: tests

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs-versions: [10, 12, 14, 16]
    name: Testing on Node JS ${{ matrix.nodejs-versions }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs-versions }}
      - run: npm install
      - run: npm test
      - run: npm run coverage
        continue-on-error: true
